version: '3.7'

services:
  django_gunicorn:
    container_name: app
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000"
    depends_on: 
      - db
  nginx:
    container_name: web_server
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "81:80"
    depends_on:
      - django_gunicorn
  db:
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432"
volumes:
  static:
  postgres_data:
